version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true
    shm_size: '2gb'  # Increase shared memory size
    command: uvicorn main:app --host 0.0.0.0 --port 8000
