version: '3'
services:
  - type: web
    name: airport-scraper
    env: python
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/app"
    plan: free
    routes:
      - type: http
        path: /
